---
title: 'Capacity Management: Weekend Discharges'
author: "Kate Nevin"
date: "1/2/2020"
output: 
  html_document:
  fig_width: 5
  fig_height: 4
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Libraries, include = FALSE}
#Install and load necessary packages --------------------
#install.packages("readxl")
#install.packages("writexl")
#install.packages("ggplot2")
#install.packages("lubridate")
#install.packages("dplyr")
#install.packages("reshape2")
#install.packages("svDialogs")
#install.packages("knitr")
#install.packages("kableExtra")

#Analysis for weekend discharge tracking
library(readxl)
library(writexl)
library(ggplot2)
library(lubridate)
library(dplyr)
library(reshape2)
library(svDialogs)
library(knitr)
library(kableExtra)
```

```{r Working directory & raw data, include = FALSE}
# Set working directory and select raw data ----------------------------
getwd()
setwd("J:\\Presidents\\HSPI-PM\\Operations Analytics and Optimization\\Projects\\Service Lines\\Capacity Management\\Data\\Discharge Billing Data")

# Data used to establish baseline and targets remains constant
raw_base <- read.csv("Crosstab_Discharges_YTD_Test 2019-11-22.csv", header = TRUE, na.strings = c("", "NA"))

# Select most recent data pull of billing data to update weekly discharge data
raw_update <- read.csv(choose.files(caption = "Select Most Recent Billing Data"), header = TRUE, na.strings = c("", "NA"))

# Save raw data in new dataframes
data_base <- raw_base
data_update <- raw_update

# Reference files and constants ----------------------------------------
ref_file <- "Analysis Reference 2019-11-22.xlsx"
site_dict <- read_excel(ref_file, sheet = "Sites")
dispo_dict <- read_excel(ref_file, sheet = "DischDispo")
dispo_dict[is.na(dispo_dict$`Discharge Disposition Desc Msx`), 1] <- "Unknown"
service_line_dict <- read_excel(ref_file, sheet = "ServiceLines")

site_order <- c("MSH", "MSQ", "MSBI", "MSB", "MSW", "MSSL")
DischDOW_Order <- c("Sat-Mon", "Tue", "Wed", "Thu", "Fri")
rpi_start <- as.Date("10/26/2019", "%m/%d/%Y")

output_location <- choose.dir(caption = "Select script output folder", default = "J:\\Presidents\\HSPI-PM\\Operations Analytics and Optimization\\Projects\\Service Lines\\Capacity Management")
```

```{r Custom functions, include = FALSE}
# Function to determine week number of year using Sat as first DOW --------------------------------------------------
weeknum <- function(x) {
  # yr <<- year(x)
  # new_yr <<- as.Date(paste0("1/1/", yr), format = "%m/%d/%Y")
  # new_yr_wkday <<- wday(new_yr, label = FALSE)
  # new_yr_sat <<- new_yr + (7 - new_yr_wkday)
  first_sat_2019 <<- as.Date("1/5/19", format = "%m/%d/%y")
  elapsed_days <<- as.numeric(x - first_sat_2019)
  week_number <<- ifelse(elapsed_days < 0, 1, as.integer(elapsed_days/7)+2)
  week_number
}

# Create a function to preprocess and format billing data -----------------
# Function as 3 input arguments:
# raw_df is the name of the existing dataframe with the raw data
# raw_df_as_char is the name of the raw data after it has been preprocessed entered as a string
# incl_df_as_char is the name of the dataframe after it has been preprocessed and exclusions removed entered as a string
preprocess <- function(raw_df, raw_df_as_char, incl_df_as_char) {
  # Format admit and discharge dates and pull out year, month, DOW, etc.
  raw_df[ , c("AdmitDate", "DischDate")] <- lapply(raw_df[ , c("Admit.Dt.Src", "Dsch.Dt.Src")], as.Date, "%m/%d/%Y")
  # raw_df$DischDate <- as.Date(raw_df$Dsch.Dt.Src, "%m/%d/%Y")
  raw_df$DischDateTime <- as.POSIXct(as.character(paste(raw_df$Dsch.Dt.Src, raw_df$Dsch.Time.Src)),  tz = "", format = "%m/%d/%Y %H:%M")
  raw_df[ , c("AdmitYr", "AdmitMo")] <- c(year(raw_df$AdmitDate), month(raw_df$AdmitDate))
  raw_df[ , c("DischYr", "DischMo", "DischHr")] <- c(year(raw_df$DischDate), month(raw_df$DischDate), hour(raw_df$DischDateTime))
  raw_df$DischDOW <- wday(raw_df$DischDate, label = TRUE, abbr = TRUE)

  # Lookup tables for site, discharge disposition, service line inclusion/eraw_dfclusion ----------------------------------------------
  # Site lookup
  raw_df$Facility.Msx <- as.character(raw_df$Facility.Msx)
  raw_df <- left_join(raw_df, site_dict, by = c("Facility.Msx" = "Facility Msx"))
  raw_df$Site <- factor(raw_df$Site, levels = site_order)

  # Discharge disposition formatting and lookup
  raw_df$Discharge.Disposition.Desc.Msx <- factor(raw_df$Discharge.Disposition.Desc.Msx, levels = c(levels(raw_df$Discharge.Disposition.Desc.Msx), "Blank"))
  raw_df[is.na(raw_df$Discharge.Disposition.Desc.Msx), "Discharge.Disposition.Desc.Msx"] <- "Blank"
  raw_df$Discharge.Disposition.Desc.Msx <- as.character(raw_df$Discharge.Disposition.Desc.Msx)
  raw_df <- left_join(raw_df, dispo_dict, by = c("Discharge.Disposition.Desc.Msx" = "Discharge Disposition Desc Msx"))
  colnames(raw_df)[ncol(raw_df)] <- "DispoRollUp"
  raw_df[is.na(raw_df$DispoRollUp), "DispoRollUp"] <- "Unknown"
  raw_df$Discharge.Disposition.Desc.Msx <- as.factor(raw_df$Discharge.Disposition.Desc.Msx)
  raw_df$DispoRollUp <- as.factor(raw_df$DispoRollUp)

  # Service line inclusion / exclusion lookup
  colnames(raw_df)[colnames(raw_df) == "Service.Desc.Msx"] <- "ServiceLine"
  raw_df$ServiceLine <- as.character(raw_df$ServiceLine)
  raw_df$ServiceLine <- ifelse(is.na(raw_df$ServiceLine), "Unknown", raw_df$ServiceLine)
  raw_df <- left_join(raw_df, service_line_dict[ , c(1,3)], by = c("ServiceLine" = "Service Desc Msx"))
  colnames(raw_df)[ncol(raw_df)] <- "ServiceLineInclude"
  raw_df$ServiceLine <- as.factor(raw_df$ServiceLine)
  raw_df$ServiceLineInclude <- as.factor(raw_df$ServiceLineInclude)

  # Exclude expired patients and specified service lines
  raw_df$Include <- ifelse(raw_df$DispoRollUp == "Expired" | raw_df$ServiceLineInclude == "No", FALSE, TRUE)

  raw_df$Week_Num <- weeknum(raw_df$DischDate)
  raw_df$Weekend <- ifelse(raw_df$DischDOW == "Sat" | raw_df$DischDOW == "Sun" | raw_df$DischDOW == "Mon", TRUE, FALSE)
  
  # Create new dataframe with only included data --------------------------------
  assign(raw_df_as_char, raw_df, envir = .GlobalEnv)
  assign(incl_df_as_char, raw_df[raw_df$Include == TRUE, ], envir = .GlobalEnv)
  
}
```

```{r Data analysis and plotting, echo = FALSE}
# Preprocess baseline data and updated weekly datasets -----------------------------
preprocess(data_base, "baseline_preprocess", "baseline_include")
preprocess(data_update, "updated_preprocess", "updated_include")


# Aggregate and format baseline data from Jan-Sep 2019 for future use --------------------------------
baseline_jansep <- baseline_include[baseline_include$DischMo <= 9, ]

serviceline_daily <- as.data.frame(baseline_jansep %>%
  group_by(Site, DischDate, DischDOW, ServiceLine) %>%
  summarize(TotalDisch = n()))

hospital_daily <- as.data.frame(baseline_jansep %>%
  group_by(Site, DischDate, DischDOW) %>%
  summarize(TotalDisch = n()))

hospital_disch_dow <- as.data.frame(hospital_daily %>%
  group_by(Site, DischDOW) %>%
  summarize(TotalDischarges = as.numeric(sum(TotalDisch)), AverageDischarges = mean(TotalDisch)))

# Total discharges by day of week for each site
total_hosp_disch_dow_tbl <- dcast(hospital_disch_dow, Site ~ DischDOW, value.var = "TotalDischarges")
total_hosp_disch_dow_tbl <- total_hosp_disch_dow_tbl[order(factor(total_hosp_disch_dow_tbl$Site, levels = site_order)), ]
rownames(total_hosp_disch_dow_tbl) <- 1:nrow(total_hosp_disch_dow_tbl)

# Average discharges by day of week for each site
avg_hosp_disch_dow_tbl <- dcast(hospital_disch_dow, Site ~ DischDOW, value.var = "AverageDischarges")
avg_hosp_disch_dow_tbl <- avg_hosp_disch_dow_tbl[order(factor(avg_hosp_disch_dow_tbl$Site, levels = site_order)), ]
rownames(avg_hosp_disch_dow_tbl) <- 1:nrow(avg_hosp_disch_dow_tbl)

avg_hosp_stats <- cbind(avg_hosp_disch_dow_tbl, 
                   WeekendTotal = avg_hosp_disch_dow_tbl$Sat + avg_hosp_disch_dow_tbl$Sun + avg_hosp_disch_dow_tbl$Mon, 
                   TargetDelta = (avg_hosp_disch_dow_tbl[ , "Mon"]*0.1))
avg_hosp_stats$TargetTotal = round(avg_hosp_stats$WeekendTotal, 0) + round(avg_hosp_stats$TargetDelta, 0)
avg_hosp_dow_print <- format(avg_hosp_disch_dow_tbl, digits = 0)
avg_hosp_stats_print <- format(avg_hosp_stats, digits = 0)

hosp_baseline_target <- avg_hosp_stats[ , c("Site", "WeekendTotal", "TargetDelta", "TargetTotal")]
colnames(hosp_baseline_target) <- c("Site", "Weekend Baseline", "Target Change", "Weekend Target")

# Aggregate, format, and track discharges by week----------------
# Determine if date is after RPI cycles began
updated_include$PostRPI <- updated_include$DischDate >= rpi_start
# Determine last Friday in data set
disch_date_df <- unique(updated_preprocess[ , c("DischDate", "DischDOW")])
rpi_end <- max(disch_date_df[disch_date_df$DischDOW == "Fri", "DischDate"])
updated_include <- updated_include[updated_include$DischDate <= rpi_end, ]


# Create daily list of discharges by site
daily_disch_site <- as.data.frame(updated_include %>%
  group_by(Site, DischDate, Week_Num, DischDOW, Weekend, PostRPI) %>%
  summarize(TotalDisch = n()))

week_num_dates <- as.data.frame(daily_disch_site %>%
  group_by(Week_Num) %>%
  summarize(SatDate = min(DischDate), FriDate = max(DischDate)))

week_num_mon <- as.data.frame(daily_disch_site[daily_disch_site$DischDOW == "Mon", ] %>%
                                group_by(Week_Num) %>%
                                summarize(MonDate = min(DischDate)))

week_num_dates <- left_join(week_num_dates, week_num_mon, by = c("Week_Num"="Week_Num"))

week_num_dates[ , c("SatDate", "FriDate", "MonDate")] <- lapply(week_num_dates[ , c("SatDate", "FriDate", "MonDate")], format, "%m/%d/%y")

week_num_dates$WeekOf <- paste0(week_num_dates$SatDate, "-", week_num_dates$FriDate)
week_num_dates$WeekendOf <- paste0(week_num_dates$SatDate, "-", week_num_dates$MonDate)
week_num_dates <- week_num_dates[ , c("Week_Num", "SatDate", "WeekOf", "WeekendOf")]

daily_disch_site <- left_join(daily_disch_site, week_num_dates, by = c("Week_Num" = "Week_Num"))
daily_disch_site[ , c("WeekOf", "SatDate")] <- lapply(daily_disch_site[ , c("WeekOf", "SatDate")], factor)

# Create new dataframes for weekdays and weekends
wkday_disch_site <- daily_disch_site[daily_disch_site$Weekend != TRUE, ]
wkend_disch_site <- daily_disch_site[daily_disch_site$Weekend == TRUE, ]

wkend_disch_site_2 <- as.data.frame(wkend_disch_site %>%
  group_by(Site, Week_Num, Weekend, PostRPI, SatDate, WeekOf, WeekendOf) %>%
  summarize(DischDOW = "Sat-Mon", DischDate = min(DischDate), TotalDisch = sum(TotalDisch)))

wkday_disch_site_2 <- wkday_disch_site[ , c("Site", "Week_Num", "SatDate", "WeekOf", "WeekendOf", "DischDate",
                                            "DischDOW", "Weekend", "PostRPI", "TotalDisch")]
wkend_disch_site_2 <- wkend_disch_site_2[ , c("Site", "Week_Num", "SatDate", "WeekOf", "WeekendOf", "DischDate",
                                            "DischDOW", "Weekend", "PostRPI", "TotalDisch")]

daily_disch_site_2 <- rbind(wkday_disch_site_2, wkend_disch_site_2)
daily_disch_site_2$DischDOW <- factor(daily_disch_site_2$DischDOW, levels = DischDOW_Order)
daily_disch_site_2 <- daily_disch_site_2[order(daily_disch_site_2$Site, daily_disch_site_2$Week_Num, daily_disch_site_2$DischDOW), ]
rownames(daily_disch_site_2) <- 1:nrow(daily_disch_site_2)

# Data analysis since RPI cycles began -----------------------------------------------
# Create dataframes with discharges since RPI cycles began
daily_disch_site_rpi <- daily_disch_site[daily_disch_site$PostRPI == TRUE, ]
daily_disch_site_2_rpi <- daily_disch_site_2[daily_disch_site_2$PostRPI == TRUE, ]

# Create table showing weekend data since RPI cycles began
wkend_totals_site <- dcast(daily_disch_site_2_rpi[daily_disch_site_2_rpi$Weekend == TRUE, ], 
                           Site ~ WeekendOf, value.var = "TotalDisch")

wkend_totals_site <- wkend_totals_site[order(factor(wkend_totals_site$Site, levels = site_order)), ]
rownames(wkend_totals_site) <- 1:nrow(wkend_totals_site)

# Create table to show baseline, target, and weekly data since RPI cycles began
wkend_rpi_tracker <- left_join(hosp_baseline_target[ , c("Site", "Weekend Baseline", "Weekend Target")], 
                              wkend_totals_site, by = c("Site" = "Site"))

# wkend_rpi_tracker$`Weekend Baseline` <- round(wkend_rpi_tracker$`Weekend Baseline`, digits = 0)

# Aggregate, format, and track discharges by day of week -----------------------------------
weekly_totals <- as.data.frame(daily_disch_site_2 %>%
  group_by(Site, Week_Num, SatDate, WeekOf, WeekendOf, PostRPI) %>%
  summarize(WkendTotal = sum(TotalDisch[Weekend == TRUE]), WklyTotal = sum(TotalDisch), WkendPercent = WkendTotal/WklyTotal*100))

weekly_totals_rpi <- melt(weekly_totals[weekly_totals$PostRPI == TRUE, ], id.vars = c("Site", "WeekOf"), measure.vars = c("WklyTotal", "WkendPercent"))
  
weekly_totals_rpi <- dcast(weekly_totals_rpi, Site + variable ~ WeekOf)

wkend_disch_trends <- left_join(wkend_disch_site_2[wkend_disch_site_2$PostRPI == TRUE, ], hosp_baseline_target, by = c("Site" = "Site"))

# Create a summary table of total weekly discharges and weekend discharges as % of total discharges-----------
site_weekly_table <- function(site) {
  weekly_totals_rpi <- weekly_totals_rpi[weekly_totals_rpi$Site == site, ]
  weekly_totals_rpi$Site <- NULL
  colnames(weekly_totals_rpi)[1] <- paste(site, "Metric")
  rownames(weekly_totals_rpi) <- 1:nrow(weekly_totals_rpi)
  weekly_totals_rpi[1, 2:ncol(weekly_totals_rpi)] <- round(weekly_totals_rpi[1, 2:ncol(weekly_totals_rpi)], digits = 0)
  weekly_totals_rpi[2, 2:ncol(weekly_totals_rpi)] <- paste(round(weekly_totals_rpi[2, 2:ncol(weekly_totals_rpi)], digits = 1), "%")
  name <- paste0(site, "WeeklyTotalPercent")
  assign(name, weekly_totals_rpi, envir = .GlobalEnv)
}

site_weekly_table("MSH")
site_weekly_table("MSQ")
site_weekly_table("MSBI")
site_weekly_table("MSB")
site_weekly_table("MSW")
site_weekly_table("MSSL")

wkend_percent <- weekly_totals_rpi[weekly_totals_rpi$variable == "WkendPercent", ]
wkend_percent$variable <- NULL
wkend_percent[ , 2:ncol(wkend_percent)] <- round(wkend_percent[ ,  2:ncol(wkend_percent)], digits = 1)
wkend_percent[ , 2:ncol(wkend_percent)] <- lapply(wkend_percent[ , 2:ncol(wkend_percent)], paste0, "%")


export_table_list = list("WeekendSummary" = wkend_rpi_tracker,
                         "MSH Total & Percent" = MSHWeeklyTotalPercent, 
                         "MSQ Total & Percent" = MSQWeeklyTotalPercent,
                         "MSBI Total & Percent" = MSBIWeeklyTotalPercent,
                         "MSB Total & Percent" = MSBWeeklyTotalPercent,
                         "MSW Total & Percent" = MSWWeeklyTotalPercent, 
                         "MSSL Total & Percent" = MSSLWeeklyTotalPercent)

# write_xlsx(export_table_list, path = paste0(output_location, "\\Weekly Discharge Stats Summary ", Sys.Date(), ".xlsx"))

# export_list = list(DischargeCensus = daily_disch_rpi,
#                    DischargeCensusWkndGroup = daily_disch_rpi2)

# write_xlsx(export_list, path = "J:\\Presidents\\HSPI-PM\\Operations Analytics and Optimization\\Projects\\Service Lines\\Capacity Management\\Data\\Script Outputs\\Export Discharge Census Data 2019-12-06.xlsx")
```

```{r Functions for plots, echo = FALSE}
# Plot discharge trends by day of week for each site ---------------------------------------------------------
sinai_colors <- c("#221f72", "#00AEEF", "#D80B8C", "#B2B3B2", "#C7C6EF", "#DDDEDD", "#FCC9E9")

stacked_bar <- function(site) {
  lookback_weeks <- 6
  stacked_data <- daily_disch_site_2_rpi[daily_disch_site_2_rpi$Site == "MSH" & 
                                           daily_disch_site_2_rpi$SatDate %in% tail(unique(daily_disch_site_2_rpi$SatDate), lookback_weeks), ]
  
  total_data <- weekly_totals[weekly_totals$Site == "MSH" & 
                                           weekly_totals$SatDate %in% tail(unique(weekly_totals$SatDate), lookback_weeks), ]
    ggplot(data = stacked_data) +
  geom_col(mapping = aes(x = SatDate, y = TotalDisch, fill = DischDOW), 
             position = position_stack(reverse = TRUE)) +
  labs(title = paste(site, "Weekly Discharges by DOW"), x = "Week Of", y = "Discharge Volume") +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5), legend.position = "bottom") +
  guides(fill = guide_legend(reverse = FALSE, title = "Day of Week")) +
  geom_text(aes(x = SatDate, y = TotalDisch, label = TotalDisch), color = "white", position = position_stack(vjust = 0.5)) +
  geom_text(data = total_data, aes(x = SatDate, y = WklyTotal, label = WklyTotal), color = "black", vjust = -0.5) +
  scale_fill_manual(values = sinai_colors) +
  scale_y_continuous(expand = c(0, 0, 0.1, 0)) 
}

weekend_trends <- function(site) {
  ggplot(data = wkend_disch_trends[wkend_disch_trends$Site == site, ], mapping = aes(x = SatDate , y = TotalDisch, group = 1)) +
    theme_bw() +
    labs(title =  paste(site,"Weekend Discharge Trends"), x = "Week Of", y = "Discharge Volume") +
    theme(plot.title = element_text(hjust=0.5),legend.position = "bottom") +
    
    geom_hline(aes(yintercept= round(`Weekend Baseline`, digits = 0), linetype = "Baseline (Jan-Sep'19)"), colour = "#8c8c8c", size = 1) +
    geom_text(aes(length(SatDate) + 0.1 ,`Weekend Baseline`, label = round(`Weekend Baseline`, digits = 0), vjust = 1.1)) +
    
    geom_hline(aes(yintercept= `Weekend Target`,linetype = "Target") , colour = "black", size = 1) +
    geom_text(aes(length(SatDate) + 0.1 ,`Weekend Target`,label = `Weekend Target`, vjust = 1.1)) +
    
    geom_point(color = "#00AEEF") +
    geom_line(aes(linetype = "Actual"), color = "#00AEEF", size = 1) +
    geom_text(aes(x= SatDate , y = TotalDisch, label = TotalDisch, vjust= -0.25, hjust = -0.15)) +
    
    scale_x_discrete(expand = c(0, 0, 0.05, 0.2)) +
    scale_y_continuous(expand = c(0, 5, 0.2, 0.5)) +
    scale_linetype_manual(name = " ",values = c(1, 2, 1),
                          guide = guide_legend(override.aes = list(color = c("#00AEEF","#8c8c8c", "black")))) #+
}
```

# Test lookback
```{r echo = FALSE}
lookback_weeks <- 5
# test <- tail(unique(daily_disch_site_2_rpi$SatDate), lookback_period)
# test2 <- daily_disch_site_2_rpi[daily_disch_site_2_rpi$SatDate %in% test, ]
bar_data <- daily_disch_site_2_rpi[daily_disch_site_2_rpi$Site == "MSH" &                                        daily_disch_site_2_rpi$SatDate  %in% tail(unique(daily_disch_site_2_rpi$SatDate), lookback_weeks), ]
total_data <- weekly_totals[weekly_totals$Site == "MSH" &                                        weekly_totals$SatDate  %in% tail(unique(weekly_totals$SatDate), lookback_weeks), ]
ggplot(data = bar_data) +
  geom_col(mapping = aes(x = SatDate, y = TotalDisch, fill = DischDOW), 
             position = position_stack(reverse = TRUE)) +
  labs(title = paste("MSH", "Weekly Discharges by DOW"), x = "Week Of", y = "Discharge Volume") +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5), legend.position = "bottom") +
  guides(fill = guide_legend(reverse = FALSE, title = "Day of Week")) +
  geom_text(aes(x = SatDate, y = TotalDisch, label = TotalDisch), color = "white", position = position_stack(vjust = 0.5)) +
  geom_text(data = total_data, aes(x = SatDate, y = WklyTotal, label = WklyTotal), color = "black", vjust = -0.5) +
  scale_fill_manual(values = sinai_colors) +
  scale_y_continuous(expand = c(0, 0, 0.1, 0))
```


```{r Play with scatter plot, echo = FALSE}
# ggplot(data = wkend_disch_site_2[wkend_disch_site_2$PostRPI == TRUE & wkend_disch_site_2$Site == "MSH", ], ) +
#   
#   theme_bw() +
#   labs(title =  paste("MSH","Weekend Discharge Trends"), x = "Week Of", y = "Discharge Volume") +
#   theme(plot.title = element_text(hjust=0.5),legend.position = "bottom") +
# 
#   geom_hline(aes(yintercept= avg_hosp_stats[avg_hosp_stats$Site == "MSH", "WeekendTotal"], linetype = "Baseline"), linetype = "dashed", colour = "#8c8c8c", size = 1) +
#   geom_text(aes(length(SatDate) + 0.1 ,avg_hosp_stats[avg_hosp_stats$Site == "MSH", "WeekendTotal"], label = round(avg_hosp_stats[avg_hosp_stats$Site == "MSH", "WeekendTotal"], digits = 0), vjust = 1.1)) +
# 
#   geom_hline(aes(yintercept= avg_hosp_stats[avg_hosp_stats$Site == "MSH", "TargetTotal"],linetype = "Target") , linetype = "solid", colour = "black", size = 1) +
#   geom_text(aes(length(SatDate) + 0.1 ,avg_hosp_stats[avg_hosp_stats$Site == "MSH", "TargetTotal"],label = avg_hosp_stats[avg_hosp_stats$Site == "MSH", "TargetTotal"], vjust = 1.1)) +
#    
#  geom_point(aes(x = SatDate , y = TotalDisch, group = 1), color = "#00AEEF") +
#  geom_line(aes(x = SatDate , y = TotalDisch, group = 1, linetype = "Actual"), color = "#00AEEF", size = 1) +
#  geom_text(aes(x= SatDate , y = TotalDisch, label = TotalDisch, vjust= -0.25, hjust = -0.15)) +
# 
#    scale_x_discrete(expand = c(0, 0, 0.05, 0.2)) +
#    scale_y_continuous(expand = c(0, 5, 0.2, 0.5)) #+
#    # scale_linetype_manual(name = "", labels = c("Actual", "Target", "Baseline"), values = c(1, 2, 1))
#      #values = c(1, 2, 1),
#    #                         guide = guide_legend(override.aes = list(color = c("#00AEEF","#8c8c8c", "black"))))

```

## RPI Progress
```{r Summary Table, echo = FALSE}
b <- rpi_tracker_df 

new_df <- b %>%
    mutate(TotalDisch = cell_spec(TotalDisch, "html", color = ifelse(TotalDisch >= Target, "green", "red"))) %>%
  melt(id.vars = c("Site", "WeekendOf", "Baseline", "Target"), measure.vars = "TotalDisch") %>%
  dcast(Site + Baseline + Target ~ WeekendOf, value.vars = "value")


new_df %>%
  kable(format = "html", escape = FALSE, digits = 0, align = "c") %>%
  kable_styling(bootstrap_options = "basic") %>%
 add_header_above(c("Weekend Discharge Summary" = ncol(new_df)), bold = TRUE, italic = TRUE, background = "#221f72", color = "white", line = TRUE) %>%
   row_spec(row = 0, bold = TRUE, italic = TRUE, background = "#221f72", color = "white") %>%
   row_spec(row = nrow(wkend_rpi_tracker), extra_css = "border-bottom: thin solid;") %>%
   column_spec(column = 1, border_right = TRUE, bold = TRUE) %>%
   column_spec(column = 3, border_right = TRUE, bold = TRUE)   




```

## MSH Weekend Discharge Dashboard
```{r MSH Data, echo = FALSE, fig.align="center"}
weekend_trends("MSH")
stacked_bar("MSH")
wkend_percent[wkend_percent$Site == "MSH", ] %>%
  kable(align = "c", row.names = FALSE) %>%
  add_header_above(c("Weekend Discharges as Percentage of Total Weekly Dischages" = ncol(wkend_percent)), bold = TRUE, italic = TRUE, background = "#221f72", color = "white", line = TRUE) %>%
  row_spec(row = 0, bold = TRUE, italic = TRUE, background = "#221f72", color = "white") %>%
  row_spec(row = 1, extra_css = "border-bottom: thin solid;")
```

## MSQ Weekend Discharge Dashboard
```{r MSQ Data, echo = FALSE, fig.align="center"}
weekend_trends("MSQ")
stacked_bar("MSQ")
kable(MSQWeeklyTotalPercent, caption = "MSQ Weekend Discharge as Percent of Total Discharges") %>%
  kable_styling(position = "center")
```

## MSBI Weekend Discharge Dashboard
```{r MSBI Data, echo = FALSE, fig.align="center"}
weekend_trends("MSBI")
stacked_bar("MSBI")
kable(MSBIWeeklyTotalPercent, caption = "MSBI Weekend Discharge as Percent of Total Discharges") %>%
  kable_styling(position = "center")
```

## MSB Weekend Discharge Dashboard
```{r MSB Data, echo = FALSE, fig.align="center"}
weekend_trends("MSB")
stacked_bar("MSB")
kable(MSBWeeklyTotalPercent, caption = "MSB Weekend Discharge as Percent of Total Discharges") %>%
  kable_styling(position = "center")
```

## MSW Weekend Discharge Dashboard
```{r MSW Data, echo = FALSE, fig.align="center"}
weekend_trends("MSW")
stacked_bar("MSW")
kable(MSWWeeklyTotalPercent, caption = "MSW Weekend Discharge as Percent of Total Discharges") %>%
  kable_styling(position = "center")
```

## MSSL Weekend Discharge Dashboard
```{r MSSL Data, echo = FALSE, fig.align="center"}
weekend_trends("MSSL")
stacked_bar("MSSL")
kable(MSSLWeeklyTotalPercent, caption = "MSSL Weekend Discharge as Percent of Total Discharges") %>%
  kable_styling(position = "center")
```
